version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

  
  catalogdb:
    image: mongo

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

  basketdb:
    image: redis:alpine

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering.Api/Dockerfile
 
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
 
  rabbitmq:
    image: rabbitmq:3-management-alpine

  existence.grpc:
    image: ${DOCKER_REGISTRY-}existencegrpc
    build:
      context: .
      dockerfile: Existence.Grpc/Dockerfile

volumes:
  mongo_data:


